### ISSUE TITLE
[v0.1.0] Iterating `world` after calling `world:delete(entityId)` throws an error

### ISSUE THREAD

**Issue by knnyism** [Ukendio/jecs#47]
When an entity is deleted, `World.__iter` tries getting the archetype of a non-existent sparse array record.

```lua
local world = jecs.World.new()

local entity = world:entity()

world:delete(entity)

for e in world do -- jecs:839: attempt to index nil with 'archetype' 
	
end
```

**Comment by Ukendio** [comment]
I have a fix for this. It will be fixed alongside the linked-records-traversal PR

**Comment by Ukendio** [comment]
This has been fixed in commit https://github.com/Ukendio/jecs/commit/735eb0152664f550be613f8299b1bc5ca1252e76
