### ISSUE TITLE
Adding a way to observe adding, setting, and removing components.

### ISSUE THREAD

**Issue by DunnoConz** [Ukendio/jecs#83]
## Describe your Feature

A way to observe changes to entities within the world. The entities ECSOnAdd, ECSOnSet, and ECSOnRemove already exist for this feature request's purpose.

## Implementation

Marcus said it would be used like this:
` Observer(Transform):event(OnAdd):on(function(entity, transform) end)`

## Considerations

Some questions that need to be answered include the following:
- Will old code break in response to this feature?
Nope.
- What are the performance impacts with this feature (if any)?
I doubt much performance impacts are expected to occur.
- How is it useful to include?
Extremely.

**Comment by Ukendio** [comment]
Solved with component hooks in https://github.com/Ukendio/jecs/pull/98
